name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - shell: bash
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
      run: |
        echo ${{ vars.FOO }}
        echo $MY_VAR >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
